// Le catalogue : 10 APIs, leur prix, leur description (sert aussi de page d'accueil découvrable)
const urlBody = { bodyType: "json", method: "POST", input: { url: "https://example.com" } };
export const CATALOG = [
  { route: "POST /v1/extract",       price: "$0.005", desc: "URL -> main content as clean markdown (JS-rendered, real browser). Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", title: "Example Domain", markdown: "# Example Domain…" } } } },
  { route: "POST /v1/render",        price: "$0.005", desc: "URL -> full HTML after JavaScript execution. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", html: "<html>…</html>" } } } },
  { route: "POST /v1/screenshot",    price: "$0.01",  desc: "URL -> PNG screenshot. Input: {url, fullPage?}",
    bazaar: { bodyType: "json", method: "POST", input: { url: "https://example.com", fullPage: false } } },
  { route: "POST /v1/pdf",           price: "$0.01",  desc: "URL -> PDF (A4, backgrounds). Input: {url}",
    bazaar: urlBody },
  { route: "POST /v1/links",        price: "$0.005", desc: "URL -> deduplicated links, internal/external with anchor text. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", count: 1, internal: [], external: [{ href: "https://iana.org", text: "Learn more" }] } } } },
  { route: "POST /v1/meta",          price: "$0.005", desc: "URL -> SEO meta, OpenGraph, canonical, JSON-LD. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", title: "Example Domain", meta: {}, jsonLd: [] } } } },
  { route: "GET /v1/fr/entreprise",  price: "$0.02",  desc: "French company lookup by name or SIREN/SIRET: officers, NAF, HQ, status. Query: ?q=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { query: "Decathlon", total: 151, results: [{ siren: "306138900", nom: "DECATHLON" }] } } } },
  { route: "GET /v1/fr/geocode",     price: "$0.005", desc: "Geocode any French address incl. overseas territories (lat/lon, score). Query: ?q=",
    bazaar: { method: "GET", input: { q: "Pointe-à-Pitre" }, output: { example: { results: [{ label: "Pointe-à-Pitre", lat: 16.23619, lon: -61.537759 }] } } } },
  { route: "GET /v1/dns",            price: "$0.005", desc: "Full DNS records for a domain: A, AAAA, MX, TXT, NS, SPF. Query: ?domain=",
    bazaar: { method: "GET", input: { domain: "example.com" }, output: { example: { domain: "example.com", a: ["1.2.3.4"], mx: [] } } } },
  { route: "GET /v1/email/validate", price: "$0.005", desc: "Email validation: syntax + domain MX check, no email sent. Query: ?email=",
    bazaar: { method: "GET", input: { email: "test@gmail.com" }, output: { example: { email: "test@gmail.com", valid: true, mx: "gmail-smtp-in.l.google.com" } } } },

  // ===== Données publiques françaises (le fossé défensif) =====
  { route: "GET /v1/fr/tva", price: "$0.005", desc: "Compute French intra-EU VAT number from a SIREN (offline, instant). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", tva: "FR51306138900" } } } },
  { route: "GET /v1/fr/vat-eu", price: "$0.02", desc: "Validate any EU VAT number via the official VIES service, returns trader name/address. Query: ?vat=",
    bazaar: { method: "GET", input: { vat: "FR40306138900" }, output: { example: { vat: "FR40306138900", valid: true, name: "DECATHLON", country: "FR" } } } },
  { route: "GET /v1/fr/commune", price: "$0.005", desc: "French commune info: population, INSEE code, postal codes, EPCI, department, region, coords. Query: ?q= or ?cp=",
    bazaar: { method: "GET", input: { q: "Basse-Terre" }, output: { example: { results: [{ nom: "Basse-Terre", insee: "97105", population: 9417, region: "Guadeloupe" }] } } } },
  { route: "GET /v1/fr/reverse-geocode", price: "$0.005", desc: "Reverse geocode lat/lon to a French address (incl. overseas). Query: ?lat=&lon=",
    bazaar: { method: "GET", input: { lat: "16.24", lon: "-61.53" }, output: { example: { label: "Pointe-à-Pitre", cp: "97110", ville: "Pointe-à-Pitre" } } } },
  { route: "GET /v1/fr/jours-feries", price: "$0.005", desc: "French public holidays for a year and zone (metropole, alsace-moselle, guadeloupe, etc.). Query: ?annee=&zone=",
    bazaar: { method: "GET", input: { annee: "2026", zone: "metropole" }, output: { example: { annee: "2026", jours: [{ date: "2026-01-01", nom: "1er janvier" }] } } } },
  { route: "GET /v1/fr/georisques", price: "$0.02", desc: "Natural & technological risks for a French commune (flood, seismic, industrial...). Query: ?insee=",
    bazaar: { method: "GET", input: { insee: "97120" }, output: { example: { insee: "97120", risques: [{ libelle: "Séisme" }] } } } },
  { route: "GET /v1/fr/carburants", price: "$0.01", desc: "Live fuel prices at stations near a French postal code (gazole, SP95/98, E85, GPL). Query: ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { cp: "97110", stations: [{ nom: "Station", prix: { gazole: 1.7 } }] } } } },
  { route: "GET /v1/fr/etablissements", price: "$0.02", desc: "French company HQ + establishment counts by SIREN (SIRET, address, status). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", nb_etablissements: 385, siege: { siret: "30613890001294" } } } } },
  { route: "GET /v1/fr/association", price: "$0.02", desc: "Search French associations (RNA) by name: SIREN, RNA id, creation date, city. Query: ?q=",
    bazaar: { method: "GET", input: { q: "Croix Rouge" }, output: { example: { total: 42, results: [{ nom: "CROIX ROUGE FRANCAISE" }] } } } },
  { route: "GET /v1/fr/dpe", price: "$0.02", desc: "Energy performance diagnostics (DPE/GES labels) for dwellings in a French area. Query: ?insee= or ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { results: [{ adresse: "...", etiquette_dpe: "D", etiquette_ges: "B" }] } } } },
  { route: "GET /v1/fr/vacances-scolaires", price: "$0.005", desc: "French school holidays by zone and year. Query: ?zone=&annee=",
    bazaar: { method: "GET", input: { zone: "Zone A", annee: "2025-2026" }, output: { example: { zone: "Zone A", vacances: [{ description: "Vacances de la Toussaint" }] } } } },
  { route: "GET /v1/fr/ecoles", price: "$0.01", desc: "French schools directory lookup by name or postal code (type, status, address, phone). Query: ?q= or ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { results: [{ nom: "Lycée", type: "Lycée", ville: "Pointe-à-Pitre" }] } } } },
  { route: "GET /v1/fr/iban", price: "$0.005", desc: "Validate an IBAN (mod-97 checksum), returns country and French bank code. Query: ?iban=",
    bazaar: { method: "GET", input: { iban: "FR7630006000011234567890189" }, output: { example: { iban: "FR76...", valid: true, pays: "FR" } } } },
  { route: "GET /v1/fr/codes-postaux", price: "$0.005", desc: "Map a French postal code to its communes (name + INSEE code). Query: ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { cp: "97110", communes: [{ nom: "Pointe-à-Pitre", insee: "97120" }] } } } },
  { route: "GET /v1/fr/cadastre", price: "$0.01", desc: "French cadastral parcel at given coordinates: parcel id, section, number, surface (IGN). Query: ?lat=&lon=",
    bazaar: { method: "GET", input: { lat: "48.8606", lon: "2.3364" }, output: { example: { idu: "75101000AI0002", section: "AI", contenance_m2: 4322 } } } },
  { route: "GET /v1/fr/valeurs-foncieres", price: "$0.02", desc: "Real French real-estate sale prices (DVF) for a commune: date, price, surface, type. Query: ?insee=&annee=",
    bazaar: { method: "GET", input: { insee: "75101", annee: "2023" }, output: { example: { insee: "75101", total: 478, mutations: [{ date: "2023-06-01", valeur_fonciere: 258000, surface_bati_m2: 22 }] } } } },
  { route: "GET /v1/fr/insee-commune", price: "$0.01", desc: "INSEE commune stats: population, area, computed density, department, region, EPCI. Query: ?insee=",
    bazaar: { method: "GET", input: { insee: "97120" }, output: { example: { insee: "97120", nom: "Pointe-à-Pitre", population: 15040, densite_hab_km2: 5419 } } } },
];
