// Le catalogue : 10 APIs, leur prix, leur description (sert aussi de page d'accueil découvrable)
const urlBody = { bodyType: "json", method: "POST", input: { url: "https://example.com" } };
export const CATALOG = [
  { route: "POST /v1/extract",       price: "$0.005", desc: "URL -> main content as clean markdown (JS-rendered, real browser). Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", title: "Example Domain", markdown: "# Example Domain…" } } } },
  { route: "POST /v1/render",        price: "$0.005", desc: "URL -> full HTML after JavaScript execution. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", html: "<html>…</html>" } } } },
  { route: "POST /v1/screenshot",    price: "$0.01",  desc: "URL -> PNG screenshot. Input: {url, fullPage?}",
    bazaar: { bodyType: "json", method: "POST", input: { url: "https://example.com", fullPage: false } } },
  { route: "POST /v1/pdf",           price: "$0.01",  desc: "URL -> PDF (A4, backgrounds). Input: {url}",
    bazaar: urlBody },
  { route: "POST /v1/links",        price: "$0.005", desc: "URL -> deduplicated links, internal/external with anchor text. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", count: 1, internal: [], external: [{ href: "https://iana.org", text: "Learn more" }] } } } },
  { route: "POST /v1/meta",          price: "$0.005", desc: "URL -> SEO meta, OpenGraph, canonical, JSON-LD. Input: {url}",
    bazaar: { ...urlBody, output: { example: { url: "https://example.com/", title: "Example Domain", meta: {}, jsonLd: [] } } } },
  { route: "GET /v1/fr/entreprise",  price: "$0.02",  desc: "French company lookup by name or SIREN/SIRET: officers, NAF, HQ, status. Query: ?q=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { query: "Decathlon", total: 151, results: [{ siren: "306138900", nom: "DECATHLON" }] } } } },
  { route: "GET /v1/fr/geocode",     price: "$0.005", desc: "Geocode any French address incl. overseas territories (lat/lon, score). Query: ?q=",
    bazaar: { method: "GET", input: { q: "Pointe-à-Pitre" }, output: { example: { results: [{ label: "Pointe-à-Pitre", lat: 16.23619, lon: -61.537759 }] } } } },
  { route: "GET /v1/dns",            price: "$0.005", desc: "Full DNS records for a domain: A, AAAA, MX, TXT, NS, SPF. Query: ?domain=",
    bazaar: { method: "GET", input: { domain: "example.com" }, output: { example: { domain: "example.com", a: ["1.2.3.4"], mx: [] } } } },
  { route: "GET /v1/email/validate", price: "$0.005", desc: "Email validation: syntax + domain MX check, no email sent. Query: ?email=",
    bazaar: { method: "GET", input: { email: "test@gmail.com" }, output: { example: { email: "test@gmail.com", valid: true, mx: "gmail-smtp-in.l.google.com" } } } },

  // ===== Données publiques françaises (le fossé défensif) =====
  { route: "GET /v1/fr/tva", price: "$0.005", desc: "Compute French intra-EU VAT number from a SIREN (offline, instant). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", tva: "FR51306138900" } } } },
  { route: "GET /v1/fr/vat-eu", price: "$0.02", desc: "Validate any EU VAT number via the official VIES service, returns trader name/address. Query: ?vat=",
    bazaar: { method: "GET", input: { vat: "FR40306138900" }, output: { example: { vat: "FR40306138900", valid: true, name: "DECATHLON", country: "FR" } } } },
  { route: "GET /v1/fr/commune", price: "$0.005", desc: "French commune info: population, INSEE code, postal codes, EPCI, department, region, coords. Query: ?q= or ?cp=",
    bazaar: { method: "GET", input: { q: "Basse-Terre" }, output: { example: { results: [{ nom: "Basse-Terre", insee: "97105", population: 9417, region: "Guadeloupe" }] } } } },
  { route: "GET /v1/fr/reverse-geocode", price: "$0.005", desc: "Reverse geocode lat/lon to a French address (incl. overseas). Query: ?lat=&lon=",
    bazaar: { method: "GET", input: { lat: "16.24", lon: "-61.53" }, output: { example: { label: "Pointe-à-Pitre", cp: "97110", ville: "Pointe-à-Pitre" } } } },
  { route: "GET /v1/fr/jours-feries", price: "$0.005", desc: "French public holidays for a year and zone (metropole, alsace-moselle, guadeloupe, etc.). Query: ?annee=&zone=",
    bazaar: { method: "GET", input: { annee: "2026", zone: "metropole" }, output: { example: { annee: "2026", jours: [{ date: "2026-01-01", nom: "1er janvier" }] } } } },
  { route: "GET /v1/fr/georisques", price: "$0.02", desc: "Natural & technological risks for a French commune (flood, seismic, industrial...). Query: ?insee=",
    bazaar: { method: "GET", input: { insee: "97120" }, output: { example: { insee: "97120", risques: [{ libelle: "Séisme" }] } } } },
  { route: "GET /v1/fr/carburants", price: "$0.01", desc: "Live fuel prices at stations near a French postal code (gazole, SP95/98, E85, GPL). Query: ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { cp: "97110", stations: [{ nom: "Station", prix: { gazole: 1.7 } }] } } } },
  { route: "GET /v1/fr/etablissements", price: "$0.02", desc: "French company HQ + establishment counts by SIREN (SIRET, address, status). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", nb_etablissements: 385, siege: { siret: "30613890001294" } } } } },
  { route: "GET /v1/fr/association", price: "$0.02", desc: "Search French associations (RNA) by name: SIREN, RNA id, creation date, city. Query: ?q=",
    bazaar: { method: "GET", input: { q: "Croix Rouge" }, output: { example: { total: 42, results: [{ nom: "CROIX ROUGE FRANCAISE" }] } } } },
  { route: "GET /v1/fr/dpe", price: "$0.02", desc: "Energy performance diagnostics (DPE/GES labels) for dwellings in a French area. Query: ?insee= or ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { results: [{ adresse: "...", etiquette_dpe: "D", etiquette_ges: "B" }] } } } },
  { route: "GET /v1/fr/vacances-scolaires", price: "$0.005", desc: "French school holidays by zone and year. Query: ?zone=&annee=",
    bazaar: { method: "GET", input: { zone: "Zone A", annee: "2025-2026" }, output: { example: { zone: "Zone A", vacances: [{ description: "Vacances de la Toussaint" }] } } } },
  { route: "GET /v1/fr/ecoles", price: "$0.01", desc: "French schools directory lookup by name or postal code (type, status, address, phone). Query: ?q= or ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { results: [{ nom: "Lycée", type: "Lycée", ville: "Pointe-à-Pitre" }] } } } },
  { route: "GET /v1/fr/iban", price: "$0.005", desc: "Validate an IBAN (mod-97 checksum), returns country and French bank code. Query: ?iban=",
    bazaar: { method: "GET", input: { iban: "FR7630006000011234567890189" }, output: { example: { iban: "FR76...", valid: true, pays: "FR" } } } },
  { route: "GET /v1/fr/codes-postaux", price: "$0.005", desc: "Map a French postal code to its communes (name + INSEE code). Query: ?cp=",
    bazaar: { method: "GET", input: { cp: "97110" }, output: { example: { cp: "97110", communes: [{ nom: "Pointe-à-Pitre", insee: "97120" }] } } } },
  { route: "GET /v1/fr/cadastre", price: "$0.01", desc: "French cadastral parcel at given coordinates: parcel id, section, number, surface (IGN). Query: ?lat=&lon=",
    bazaar: { method: "GET", input: { lat: "48.8606", lon: "2.3364" }, output: { example: { idu: "75101000AI0002", section: "AI", contenance_m2: 4322 } } } },
  { route: "GET /v1/fr/valeurs-foncieres", price: "$0.02", desc: "Real French real-estate sale prices (DVF) for a commune: date, price, surface, type. Query: ?insee=&annee=",
    bazaar: { method: "GET", input: { insee: "75101", annee: "2023" }, output: { example: { insee: "75101", total: 478, mutations: [{ date: "2023-06-01", valeur_fonciere: 258000, surface_bati_m2: 22 }] } } } },
  { route: "GET /v1/fr/insee-commune", price: "$0.01", desc: "INSEE commune stats: population, area, computed density, department, region, EPCI. Query: ?insee=",
    bazaar: { method: "GET", input: { insee: "97120" }, output: { example: { insee: "97120", nom: "Pointe-à-Pitre", population: 15040, densite_hab_km2: 5419 } } } },
  { route: "GET /v1/fr/meteo", price: "$0.005", desc: "Current weather + up to 7-day forecast for any coordinates (France & overseas), French descriptions. Query: ?lat=&lon=&jours=",
    bazaar: { method: "GET", input: { lat: "16.24", lon: "-61.53", jours: "3" }, output: { example: { actuel: { temperature: 30.7, description: "Principalement clair" }, previsions: [{ date: "2026-07-22", tmax: 31 }] } } } },
  { route: "GET /v1/fr/rge", price: "$0.02", desc: "RGE-certified renovation contractors near a French postal code (name, trade, phone, email). Query: ?cp=&domaine=",
    bazaar: { method: "GET", input: { cp: "97110", domaine: "Isolation" }, output: { example: { cp: "97110", artisans: [{ nom: "EURL X", domaine: "Isolation", telephone: "0590..." }] } } } },
  { route: "GET /v1/fr/rge-check", price: "$0.01", desc: "Check whether a French company (by SIRET) is RGE-certified, with its qualifications. Query: ?siret=",
    bazaar: { method: "GET", input: { siret: "49974034800028" }, output: { example: { siret: "49974034800028", rge: true, qualifications: [{ domaine: "Architecte" }] } } } },
  { route: "GET /v1/fr/transport", price: "$0.01", desc: "Public-transit & mobility open datasets for a French area with GTFS/NeTEx/GBFS feed URLs. Query: ?q=",
    bazaar: { method: "GET", input: { q: "Guadeloupe" }, output: { example: { query: "Guadeloupe", datasets: [{ titre: "...", type: "public-transit", feeds: [{ format: "GTFS", url: "https://..." }] }] } } } },
  { route: "GET /v1/fr/irve", price: "$0.01", desc: "EV charging stations in a French commune: operator, power, connectors, access, coords (IRVE). Query: ?insee=",
    bazaar: { method: "GET", input: { insee: "75101" }, output: { example: { insee: "75101", bornes: [{ station: "QPARK RIVOLI", operateur: "IZIVIA", puissance_kw: 22 }] } } } },
  { route: "GET /v1/fr/bodacc", price: "$0.02", desc: "BODACC legal announcements for a French company by SIREN (filings, sales, insolvency, changes). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", total: 98, annonces: [{ date: "2026-07-09", type: "Avis initial", famille: "Dépôts des comptes" }] } } } },
  { route: "GET /v1/fr/bio", price: "$0.02", desc: "Certified organic (AB) operators in France by department and/or text search: farms, processors, productions. Query: ?departement=&q=",
    bazaar: { method: "GET", input: { departement: "971", q: "vignoble" }, output: { example: { total: 475, operateurs: [{ nom: "...", numeroBio: 136219, activites: ["Production"] }] } } } },

  // ===== APIs composites (valeur = agrégation / calcul, pas la donnée brute) =====
  { route: "GET /v1/fr/entreprise-360", price: "$0.05", desc: "Full French company report in ONE call: identity, VAT, HQ, officers, establishments, finances, legal notices (BODACC), RGE cert. Aggregates 3 sources. Free trial: /free/entreprise-360. Query: ?q= or ?siren=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { found: true, identite: { siren: "306138900", tva: "FR51306138900" }, annonces_legales: { total: 98 } } } } },
  { route: "GET /v1/fr/estimation-immo", price: "$0.08", desc: "Real-estate price estimate (AVM) computed from real DVF sale comparables: €/m² median + range and value for a surface. Free trial: /free/estimation-immo. Query: ?adresse=&surface=&type=appartement|maison",
    bazaar: { method: "GET", input: { adresse: "10 rue de Rivoli Paris", surface: "50", type: "appartement" }, output: { example: { ville: "Paris", prix_m2: { median: 12110 }, estimation: { valeur_estimee: 605476 } } } } },
  { route: "GET /v1/fr/bilans", price: "$0.10", desc: "French company annual accounts & financial statements (revenue, net income, capital) + list of filed accounts, via INPI RNE (auth-gated source). Query: ?siren=",
    bazaar: { method: "GET", input: { siren: "306138900" }, output: { example: { siren: "306138900", denomination: "DECATHLON", comptes_annuels_deposes: [{ date_cloture: "2024-12-31" }] } } } },
  { route: "GET /v1/fr/score-entreprise", price: "$0.15", desc: "Company solidity/risk score 0-100 for a French company: crosses INPI financials (revenue/profit trend), BODACC legal proceedings, age, status. Replaces a paid solvency report. Free trial: /free/score-entreprise. Query: ?q= or ?siren=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { siren: "306138900", score: 82, niveau: "solide" } } } },
  { route: "GET /v1/fr/analyse-immo", price: "$0.15", desc: "Real-estate investment scorecard for an address: DVF value estimate + energy (DPE) + natural risks + demographics + rental yield estimate. Query: ?adresse=&surface=&type=appartement|maison",
    bazaar: { method: "GET", input: { adresse: "10 rue de Rivoli Paris", surface: "50" }, output: { example: { ville: "Paris", estimation: { prix_m2_median: 12110 }, score_investissement: 73 } } } },
  { route: "GET /v1/fr/kyb", price: "$0.20", desc: "Know-Your-Business compliance dossier for a French company in one call: identity, VAT + VIES validation, officers, financial health (INPI), legal proceedings (BODACC), risk verdict. Free trial: /free/kyb. Query: ?q= or ?siren=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { siren: "306138900", verdict: "CONFORME", fiscal: { tva_validee_vies: true } } } } },
  { route: "GET /v1/fr/etude-implantation", price: "$0.25", desc: "Business location study: competitor saturation (same activity in commune), demographics, commercial real-estate prices, opportunity score. Query: ?activite=&commune=",
    bazaar: { method: "GET", input: { activite: "boulangerie", commune: "Pointe-à-Pitre" }, output: { example: { commune: "Pointe-à-Pitre", concurrents_actifs: 56, habitants_par_concurrent: 268, score_opportunite: 45 } } } },
  { route: "GET /v1/fr/reseau-dirigeant", price: "$0.15", desc: "All French companies linked to a person (director search) with active/ceased flags and fraud-risk level. Query: ?nom=&prenom=",
    bazaar: { method: "GET", input: { nom: "Arnault", prenom: "Bernard" }, output: { example: { total_societes: 40, cessees: 2, niveau_alerte: "modérée" } } } },
  { route: "GET /v1/fr/concurrents", price: "$0.15", desc: "Competitive landscape of a French company: same-NAF rivals in its area ranked by revenue, with CA position. Query: ?q= or ?siren= &zone=departement|region",
    bazaar: { method: "GET", input: { q: "Decathlon", zone: "departement" }, output: { example: { total_marche: 297, top_concurrents: [{ nom: "...", finances: { ca: 1000000 } }] } } } },
  { route: "GET /v1/fr/verif-artisan", price: "$0.15", desc: "Verify a French contractor before hiring: company health, age, RGE certification, insolvency proceedings, trust level. Query: ?q= or ?siren=",
    bazaar: { method: "GET", input: { q: "EURL LAURENT LAVALL" }, output: { example: { confiance: "élevée", certifie_rge: true, procedures_collectives: 0 } } } },
  { route: "GET /v1/fr/valorisation", price: "$0.20", desc: "Company valuation estimate from public financials (revenue & earnings multiples), with range. Query: ?q= or ?siren=",
    bazaar: { method: "GET", input: { q: "Decathlon" }, output: { example: { chiffre_affaires: 16207285000, valorisation: { estimation_centrale: 15000000000 } } } } },
  { route: "GET /v1/uk/company", price: "$0.02", desc: "UK company profile (Companies House): status, incorporation, SIC codes, registered office, accounts due dates, insolvency/charges flags. Query: ?q= or ?number=",
    bazaar: { method: "GET", input: { q: "Tesco PLC" }, output: { example: { company_number: "00445790", name: "TESCO PLC", status: "active" } } } },
  { route: "GET /v1/uk/officers", price: "$0.02", desc: "UK company directors/officers (Companies House): name, role, appointment/resignation, nationality. Query: ?q= or ?number=",
    bazaar: { method: "GET", input: { number: "00445790" }, output: { example: { total: 12, officers: [{ name: "...", role: "director" }] } } } },
  { route: "GET /v1/uk/psc", price: "$0.03", desc: "UK beneficial owners — Persons with Significant Control (Companies House), key for KYB/AML. Query: ?q= or ?number=",
    bazaar: { method: "GET", input: { number: "00445790" }, output: { example: { total: 1, controllers: [{ name: "...", nature_of_control: ["ownership-of-shares-75-to-100-percent"] }] } } } },
  { route: "GET /v1/uk/company-check", price: "$0.15", desc: "UK company KYB verdict in one call: status, accounts/filing compliance, insolvency history, officers, beneficial owners. Query: ?q= or ?number=",
    bazaar: { method: "GET", input: { q: "Tesco PLC" }, output: { example: { name: "TESCO PLC", verdict: "PASS", active_officers: 12 } } } },
  { route: "GET /v1/us/company", price: "$0.02", desc: "US public company profile (SEC EDGAR): name, CIK, tickers, exchange, SIC, state, fiscal year, latest filing. Query: ?ticker= or ?cik=",
    bazaar: { method: "GET", input: { ticker: "AAPL" }, output: { example: { cik: "0000320193", name: "Apple Inc.", exchanges: ["Nasdaq"] } } } },
  { route: "GET /v1/us/financials", price: "$0.05", desc: "US public company key annual financials from SEC XBRL: revenue, net income, assets, liabilities, equity, cash (3 years). Query: ?ticker= or ?cik=",
    bazaar: { method: "GET", input: { ticker: "AAPL" }, output: { example: { name: "Apple Inc.", net_income: [{ end: "2025-09-27", value: 112010000000 }] } } } },
  { route: "GET /v1/us/filings", price: "$0.02", desc: "Recent SEC filings for a US company (10-K, 10-Q, 8-K...) with dates and document URLs. Query: ?ticker= or ?cik= &type=",
    bazaar: { method: "GET", input: { ticker: "AAPL", type: "10-K" }, output: { example: { name: "Apple Inc.", filings: [{ form: "10-K", filed: "2025-11-01" }] } } } },
  { route: "GET /v1/us/snapshot", price: "$0.10", desc: "One-call US company financial snapshot: revenue, growth, net income, margin, ROE, profitability from SEC XBRL. Query: ?ticker= or ?cik=",
    bazaar: { method: "GET", input: { ticker: "AAPL" }, output: { example: { name: "Apple Inc.", revenue_growth_pct: 6.2, net_margin_pct: 24.3 } } } },
];
